version: '3'

services:
  httpd:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      environment:
        - OS # Defined on Windows but not on other platforms
    volumes:
      - ..:/workspace
      - csxl.unc.edu-node_modules:/workspace/frontend/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: postgres:15.2
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - '5432:5432'
    volumes:
      - csxl.unc.edu-postgres:/var/lib/postgresql/data

volumes:
  csxl.unc.edu-node_modules:
  csxl.unc.edu-postgres: